export const getScheduleData = (marhala) => {
  const schedules = {
    1: [
      { date: "Jan 13", title: "Lesson 1", type: "lesson" },
      { date: "Jan 27", title: "Lesson 2", type: "lesson" },
      { date: "Feb 10", title: "Lesson 3", type: "lesson" },
      { date: "Feb 24", title: "Lesson 4", type: "lesson" },
      { date: "Mar 10", title: "Lesson 5", type: "lesson" },
      { date: "Mar 24", title: "Lesson 6", type: "lesson" },
      { date: "Apr 7", title: "Lesson 7", type: "lesson" },
      { date: "Apr 21", title: "Lesson 8", type: "lesson" },
      { date: "May 5", title: "Lesson 9", type: "lesson" },
      { date: "Apr 28", title: "Quiz 1", type: "quiz" },
      { date: "Jun 16", title: "Quiz 2", type: "quiz" },
      { date: "Jul 7", title: "Exam", type: "exam" },
      { date: "Jul 21", title: "Results", type: "results" },
      { date: "Jul 23", title: "Results", type: "results" },
      { date: "Jul 25", title: "Results", type: "results" },
      { date: "Jul 27", title: "Results", type: "results" },
    ],
    2: [
      { date: "Jan 13", title: "Lesson 1", type: "lesson" },
      { date: "Jan 27", title: "Lesson 2", type: "lesson" },
      { date: "Feb 10", title: "Lesson 3", type: "lesson" },
      { date: "Feb 24", title: "Lesson 4", type: "lesson" },
      { date: "Mar 10", title: "Lesson 5", type: "lesson" },
      { date: "Mar 24", title: "Lesson 6", type: "lesson" },
      { date: "Apr 7", title: "Lesson 7", type: "lesson" },
      { date: "Apr 21", title: "Lesson 8", type: "lesson" },
      { date: "May 5", title: "Lesson 9", type: "lesson" },
      { date: "Apr 28", title: "Quiz 1", type: "quiz" },
      { date: "Jun 16", title: "Quiz 2", type: "quiz" },
      { date: "Jul 7", title: "Exam", type: "exam" },
      { date: "Jul 21", title: "Halaqah", type: "lesson" },
      { date: "Jul 23", title: "Tadreeb", type: "lesson" },
      { date: "Jul 25", title: "Results", type: "results" },
      { date: "Jul 27", title: "Results", type: "results" },
    ],
    3: [
      { date: "Jan 13", title: "Lesson 1", type: "lesson" },
      { date: "Jan 27", title: "Lesson 2", type: "lesson" },
      { date: "Feb 10", title: "Lesson 3", type: "lesson" },
      { date: "Feb 24", title: "Lesson 4", type: "lesson" },
      { date: "Mar 10", title: "Lesson 5", type: "lesson" },
      { date: "Mar 24", title: "Lesson 6", type: "lesson" },
      { date: "Apr 7", title: "Lesson 7", type: "lesson" },
      { date: "Apr 21", title: "Lesson 8", type: "lesson" },
      { date: "May 5", title: "Lesson 9", type: "lesson" },
      { date: "Apr 28", title: "Quiz 1", type: "quiz" },
      { date: "Jun 16", title: "Quiz 2", type: "quiz" },
      { date: "Jul 7", title: "Exam", type: "exam" },
      { date: "Jul 21", title: "Halaqah", type: "lesson" },
      { date: "Jul 23", title: "Tadreeb", type: "lesson" },
      { date: "Jul 25", title: "Results", type: "results" },
      { date: "Jul 27", title: "Results", type: "results" },
    ],
    4: [
      { date: "Jan 13", title: "Lesson 1", type: "lesson" },
      { date: "Jan 27", title: "Lesson 2", type: "lesson" },
      { date: "Feb 10", title: "Lesson 3", type: "lesson" },
      { date: "Feb 24", title: "Lesson 4", type: "lesson" },
      { date: "Mar 10", title: "Lesson 5", type: "lesson" },
      { date: "Mar 24", title: "Lesson 6", type: "lesson" },
      { date: "Apr 7", title: "Lesson 7", type: "lesson" },
      { date: "Apr 21", title: "Lesson 8", type: "lesson" },
      { date: "May 5", title: "Lesson 9", type: "lesson" },
      { date: "Apr 28", title: "Quiz 1", type: "quiz" },
      { date: "Jun 16", title: "Quiz 2", type: "quiz" },
      { date: "Jul 7", title: "Exam", type: "exam" },
      { date: "Jul 21", title: "Halaqah", type: "lesson" },
      { date: "Jul 23", title: "Tadreeb", type: "lesson" },
      { date: "Jul 25", title: "Results", type: "results" },
      { date: "Jul 27", title: "Results", type: "results" },
    ],
  };
  return schedules[marhala] || schedules[1];
};